### ISSUE TITLE
Peer Code Review

### ISSUE THREAD

**Issue by eduardosancho** [JohnFTitor/toDoList#5]
Great job, you totally nailed this project! 
II didn't find any particular issue, to me, your implementation is both elegant and practical.

![confeetti](https://media.giphy.com/media/26u4cqiYI30juCOGY/giphy.gif)

**Comment by danielufeli** [comment]
Nice one bro well done, just wanted to add that you can mark the checkbox once selected.

**Comment by JohnFTitor** [comment]
Thanks for the review guys!

I'll implement the checkbox change. I'm glad you liked the project.

<img src="https://media3.giphy.com/media/d1D7hHL2TE5QSKc7Is/giphy.gif"/>
