### ISSUE TITLE
Peer to Peer to Code Review

### ISSUE THREAD

**Issue by zhadier** [JohnFTitor/toDoList#8]
## Hey Guys, Great job on the testing. It's actually impressive what you guys have accomplished.
- The work you have done is exceptional, I don't have much to review but I guess I can suggest you guys this link as an additional source of information.

https://medium.com/@rickhanlonii/understanding-jest-mocks-f0046c68e53c

<img src="https://media4.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif"/>

**Comment by JohnFTitor** [comment]
Thanks for the resource @zhadier. I'll definitely check it!  

<img src="https://media0.giphy.com/media/VBc6l3CqQonqo/giphy.gif"/>
